MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 12.0            # [osx and x86_64]
c_stdlib_version:  # [osx and x86_64]
  - "12.0"                # [osx and x86_64]
channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb main
