MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.14            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb main
numpy:
  - 1.21   # [not (osx and arm64) and not win]
  - 1.21
  - 1.21
  - 1.21
python:
  - 3.7.* *_cpython   # [not (osx and arm64) and not win]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
python_impl:
  - cpython   # [not (osx and arm64) and not win]
  - cpython
  - cpython
  - cpython
pyarrow:
  - 9.0.0
  - 10.0.1
  - 11.0.0
pin_run_as_build:
  pyarrow:
    min_pin: x.x.x
    max_pin: x.x.x
