MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.14            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb main
numpy:
  - 1.20   # [not (osx and arm64) and not win]
  - 1.21
python:
  - 3.7.* *_cpython   # [not (osx and arm64) and not win]
  - 3.10.* *_cpython
python_impl:
  - cpython   # [not (osx and arm64) and not win]
  - cpython
pin_run_as_build:
  libarrow:
    min_pin: x.x.x
    max_pin: x.x.x
