MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
c_stdlib_version:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb main

# Required to continue building python 3.9
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
is_python_min:
  - true
  - false
  - false
  - false
