{% set name = "tiledb-vcf" %}
{% set version = "0.22.2" %}
{% set sha256 = "72e1c108a691be000768e07a05c599a7b804154df96e8a2d1056a969fb1dc23b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-VCF/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: true  # [win or linux32 or py2k]

outputs:
  - name: libtiledbvcf
    version: {{ version }}
    script: build-libtiledbvcf.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
      host:
        - tiledb 2.14.*
        - htslib >=1.15
      run:
        - tiledb 2.14.*
        - htslib >=1.15
    test:
      files:
        - test-cli.sh
      commands:
        - tiledbvcf version
        # verify libhts is linked
        - ldd ${PREFIX}/lib/libtiledbvcf.so | grep libhts  # [linux]
        - otool -L ${PREFIX}/lib/libtiledbvcf.dylib | grep libhts  # [osx]
        # verify libdeflate is linked to libhts
        - ldd ${PREFIX}/lib/libhts.so.* | grep libdeflate  # [linux]
        - otool -L ${PREFIX}/lib/libhts.*.dylib | grep libdeflate  # [osx]
        - tiledbvcf create --uri /tmp/test-tiledbvcf-conda
        - bash test-cli.sh

  - name: tiledbvcf-py
    version: {{ version }}
    script: build-tiledbvcf-py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - numpy
        - libtiledbvcf {{ version }}
        - python
        - pyarrow 9.0.*
        - pybind11 >=2.5
        - wheel >=0.30
        - setuptools >=18.0
        - setuptools_scm 6.0.1
        - setuptools_scm_git_archive
        - fsspec<2023.3.0
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow 9.0.*
        - pandas
    imports:
      - tiledbvcf
    test:
      files:
        - test-api.py
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"
        - python test-api.py

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient variant-call data storage and retrieval library using the TileDB storage library.'
  description: |
    TileDB-VCF is the python interface to the TileDB-VCF library.
  doc_url: https://docs.tiledb.com/developer/tiledbvcf/introduction
  dev_url: https://github.com/TileDB-Inc/TileDB-VCF

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
    - jdblischak
