{% set name = "tiledb-vcf" %}
{% set version = "0.33.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Have to use Git tag as source so that setuptools-scm
  # can auto-configure the version number
  git_url: https://github.com/TileDB-Inc/TileDB-VCF.git
  git_rev: {{ version }}
  git_depth: -1

build:
  number: 1
  skip: true  # [linux32 or py2k]

outputs:
  - name: libtiledbvcf
    version: {{ version }}
    script: build-libtiledbvcf.sh  # [not win]
    script: build-libtiledbvcf.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - git
        - cmake
        - make  # [not win]
        # Helps resolve Illegal instruction in tests
        - libcxx <18          # [osx and x86_64]
      host:
        - htslib >=1.15  # [not win]
        - m2w64-htslib >=1.15  # [win]
        - tiledb 2.24.*
        # Helps resolve Illegal instruction in tests
        - libcxx <18          # [osx and x86_64]
        - aws-c-io 0.14.9     # [osx and x86_64]
        - aws-crt-cpp 0.27.2  # [osx and x86_64]
        - c-ares 1.28.1       # [osx and x86_64]
      run:
        - htslib >=1.15  # [not win]
        - m2w64-htslib >=1.15  # [win]
        # Helps resolve Illegal instruction in tests
        - libcxx <18     # [osx and x86_64]
        - c-ares 1.28.1  # [osx and x86_64]
    test:
      files:  # [not win]
        - test-cli.sh  # [not win]
      commands:
        - tiledbvcf version
        # verify libhts is linked
        - ldd ${PREFIX}/lib/libtiledbvcf.so | grep libhts  # [linux]
        - otool -L ${PREFIX}/lib/libtiledbvcf.dylib | grep libhts  # [osx]
        # verify libdeflate is linked to libhts
        - ldd ${PREFIX}/lib/libhts.so.* | grep libdeflate  # [linux]
        - otool -L ${PREFIX}/lib/libhts.*.dylib | grep libdeflate  # [osx]
        - tiledbvcf create --uri /tmp/test-tiledbvcf-conda  # [not win]
        - tiledbvcf create --uri %SRC_DIR%\test-tiledbvcf-conda  # [win]
        - bash test-cli.sh  # [not win]

  - name: tiledbvcf-py
    version: {{ version }}
    script: build-tiledbvcf-py.sh  # [not win]
    script: build-tiledbvcf-py.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [not win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pyarrow                                # [build_platform != target_platform]
        - pyarrow-hotfix                         # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        # Helps resolve Illegal instruction in tests
        - libcxx <18          # [osx and x86_64]
      host:
        - numpy
        - libtiledbvcf {{ version }}
        - python
        - pyarrow
        - pyarrow-hotfix
        - pybind11 >=2.5
        - wheel >=0.30
        - setuptools >=18.0
        - setuptools_scm >=6.0.1
        - setuptools_scm_git_archive
        - pip
        - scikit-build-core
        # Helps resolve Illegal instruction in tests
        - libcxx <18          # [osx and x86_64]
        - aws-c-io 0.14.9     # [osx and x86_64]
        - aws-crt-cpp 0.27.2  # [osx and x86_64]
        - c-ares 1.28.1       # [osx and x86_64]
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.27') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow
        - pyarrow-hotfix
        - pandas
        # Helps resolve Illegal instruction in tests
        - libcxx <18     # [osx and x86_64]
        - c-ares 1.28.1  # [osx and x86_64]
    imports:
      - tiledbvcf
    test:
      files:
        - test-api.py
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"
        - python test-api.py

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient variant-call data storage and retrieval library using the TileDB storage library.'
  description: |
    TileDB-VCF is the python interface to the TileDB-VCF library.
  doc_url: https://docs.tiledb.com/developer/tiledbvcf/introduction
  dev_url: https://github.com/TileDB-Inc/TileDB-VCF

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
    - jdblischak

# touch to re-force CI (re-run button not working, IDK why)
