{% set name = "tiledb-vcf" %}
{% set version = "0.10.0" %}
{% set sha256 = "e611e40ae5e7b5868687b8df7cc6124c0d65bc3128e557023d7525c3597132ba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #git_url: https://github.com/TileDB-Inc/TileDB-VCF.git
  #git_rev: {{ version }}
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/TileDB-VCF/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win or linux32 or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
    - make
  run:
    - htslib >=1.10
    - tiledb 2.3.*
  host:
    - htslib >=1.10
    - tiledb 2.3.*

outputs:
  - name: libtiledbvcf
    version: {{ version }}
    script: install-libtiledbvcf.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
      host:
        - htslib >=1.10
        - tiledb 2.3.*
      run:
        - htslib >=1.10
        - tiledb 2.3.*
    test:
      commands:
        - tiledbvcf version

  - name: tiledbvcf-py
    version: {{ version }}
    script: build-tiledbvcf-py.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
      host:
        - {{ pin_compatible('numpy', lower_bound='1.16') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow 3.0.*
        - pybind11
        - rpdb
        - wheel
        - setuptools
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow 3.0.*
        - pybind11
        - setuptools
        - pandas
    imports:
      - tiledbvcf
    test:
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient variant-call data storage and retrieval library using the TileDB storage library.'
  description: |
    TileDB-VCF is the python interface to the TileDB-VCF library.
  doc_url: https://docs.tiledb.com/developer/tiledbvcf/introduction
  dev_url: https://github.com/TileDB-Inc/TileDB-VCF

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
