{% set name = "tiledb-vcf" %}
{% set version = "0.25.3" %}
{% set sha256 = "46111c156983101afc3cc3f5f1affef4d05cd28f69b6650ffac25cdedbe1dab5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-VCF/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Update-python-pybind11-to-use-c-17.patch

build:
  number: 0
  skip: true  # [linux32 or py2k]

outputs:
  - name: libtiledbvcf
    version: {{ version }}
    script: build-libtiledbvcf.sh  # [not win]
    script: build-libtiledbvcf.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - htslib >=1.15  # [not win]
        - m2w64-htslib >=1.15  # [win]
        - tiledb 2.16.*
      run:
        - htslib >=1.15  # [not win]
        - m2w64-htslib >=1.15  # [win]
        - tiledb 2.16.*
    test:
      files:  # [not win]
        - test-cli.sh  # [not win]
      commands:
        - tiledbvcf version
        # verify libhts is linked
        - ldd ${PREFIX}/lib/libtiledbvcf.so | grep libhts  # [linux]
        - otool -L ${PREFIX}/lib/libtiledbvcf.dylib | grep libhts  # [osx]
        # verify libdeflate is linked to libhts
        - ldd ${PREFIX}/lib/libhts.so.* | grep libdeflate  # [linux]
        - otool -L ${PREFIX}/lib/libhts.*.dylib | grep libdeflate  # [osx]
        - tiledbvcf create --uri /tmp/test-tiledbvcf-conda  # [not win]
        - tiledbvcf create --uri %SRC_DIR%\test-tiledbvcf-conda  # [win]
        - bash test-cli.sh  # [not win]

  - name: tiledbvcf-py
    version: {{ version }}
    script: build-tiledbvcf-py.sh  # [not win]
    script: build-tiledbvcf-py.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pyarrow 9.0.0                          # [py<=37 and build_platform != target_platform]
        - pyarrow {{ pyarrow }}                  # [py>=38 and build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - numpy
        - libtiledbvcf {{ version }}
        - python
        - pyarrow 9.0.0  # [py<=37]
        - pyarrow  {{ pyarrow }}  # [py>=38]
        - pybind11 >=2.5
        - wheel >=0.30
        - setuptools >=18.0
        - setuptools_scm 6.0.1
        - setuptools_scm_git_archive
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - {{ pin_compatible('pyarrow', max_pin='x.x.x') }}
        - pandas
    imports:
      - tiledbvcf
    test:
      files:
        - test-api.py
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"
        - python test-api.py

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient variant-call data storage and retrieval library using the TileDB storage library.'
  description: |
    TileDB-VCF is the python interface to the TileDB-VCF library.
  doc_url: https://docs.tiledb.com/developer/tiledbvcf/introduction
  dev_url: https://github.com/TileDB-Inc/TileDB-VCF

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
    - jdblischak
