build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
channels:
  sources:
    - conda-forge
  targets:
    - ["tiledb", "main"]
github:
  user_or_org: TileDB-Inc
  branch_name: master
  tooling_branch_name: main
